name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Package for Windows
      run: |
        npm run package-win
      
    - name: Package for Linux
      run: |
        npm run package-linux
        
    - name: Package for Windows
      run: |
        npm run package-mac
